version: '3.4'
services:
  videochat-db:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: video-chat
      POSTGRES_TCP_PORT: 5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - videochat-network
  videochat-service:
    build: ./
    image: video-chat
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.APPLICATION.NAME: video-chat
      SPRING.DATASOURCE.URL: jdbc:postgresql://videochat-db:5432/video-chat?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: admin
      SPRING.DATASOURCE.PASSWORD: admin123
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - videochat-db
    networks:
      - videochat-network
networks:
  videochat-network:
    driver: bridge
      
